/*CREAMOS LA BD */
CREATE DATABASE ExamenFinal

/*CREAMOS LA TABLA DE USUARIO CON SUS RESPECTIVOS CAMPOS */
CREATE TABLE Usuario
(IDUSUARIO INT PRIMARY KEY IDENTITY(1,1),
 CEDULA VARCHAR(50), 
 NOMBRE VARCHAR(50),
 APELLIDO VARCHAR(50),
 DIRECCION VARCHAR(50));

 /*CREAMOS LA TABLA DE MATERIAS CON SUS RESPECTIVOS CAMPOS Y LA RELACIONAMOS CON LA TABLA DE NOTAS*/
 CREATE TABLE Materias (IDMATERIAS INT PRIMARY KEY IDENTITY(1,2),
  MATERIA VARCHAR(50));

 /*CREAMOS LA TABLA DE NOTAS CON SUS RESPECTIVOS CAMPOS Y LA RELACIONAMOS CON LA TABLA DE USUARIO 
 Y LA TABLA DE MATERIAS */
 CREATE TABLE NOTAS (IDNOTAS INT PRIMARY KEY IDENTITY (2,2), NOTA FLOAT,
 IDUSUARIO INT,
 FOREIGN KEY (IDUSUARIO) REFERENCES Usuario(IDUSUARIO),
 IDMATERIAS INT,
 FOREIGN KEY (IDMATERIAS) REFERENCES Materias(IDMATERIAS),
 );

 /*HACEMOS LOS SELECT PARA CONSULTAR  LAS DIFERENTES TABLAS*/
 SELECT * FROM Usuario
 SELECT * FROM NOTAS
 SELECT * FROM Materias

 /*AQUI USAMOS UN ALTER TABLE PARA AGREGAR A LA TABLA DE MATERIAS EL IDNOTAS DE LA TABLA NOTAS*/
ALTER TABLE Materias
ADD IDNOTAS INT; 

/*AQUI USAMOS EL ALTER TABLE PARA PODER RELACIONAR LAS TABLAS DE NOTAS CON LA TABLA DE MATERIAS*/
ALTER TABLE Materias
ADD FOREIGN KEY (IDNOTAS) REFERENCES NOTAS(IDNOTAS); 